apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  acme:
    email: nadzeya@maumap.com
